# Generated by Django 4.0.2 on 2022-05-05 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_alter_article_publish_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(to='blog.Category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 5, 14, 47, 569692)),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.BooleanField(default=True, verbose_name='آیا نمایش داده شود؟'),
        ),
    ]
